apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vm-microservice
  namespace: vm-apps
spec:
  targetNamespace: frontend
  serviceAccountName: vm-apps-sa
  chart:
    spec:
      chart: charts/vm-microservice
      sourceRef:
        kind: GitRepository
        name: vm-microservice
      valuesFiles:
        - charts/vm-microservice/values.yaml
        - charts/vm-microservice/values-k8s.yaml
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
  interval: 1m
