apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vamika-frontend
  namespace: vm-apps
spec:
  targetNamespace: frontend
  serviceAccountName: vm-apps-sa
  chart:
    spec:
      chart: charts/vm-frontend
      sourceRef:
        kind: GitRepository
        name: vamika-frontend
  values:
    image:
      repository: kubevamshi/vamika-frontend
      tag: "v1.0.0-20250214200831"
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
  interval: 1m
