apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vm-apps
  namespace: vm-apps
spec:
  interval: 1m0s
  serviceAccountName: vm-apps-sa
  path: apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: vm-apps